import './App.css';
import CV from './assets/cv.pdf';
const linkedin = 'https://www.linkedin.com/in/joshua-f-cassell-iii-347aab81/';
const projects = [
 ['DailyActivity', 'CARE & CONNECTION', 'Founder · Lead Architect', 'A shared picture of everyday life.', 'Designed to bring behavior observations, routines, learning progress, and communication moments together for families, educators, and caregivers.', 'https://dailyactivity.org'],
 ['Talkeez AAC', 'ACCESSIBLE COMMUNICATION', 'Founder · Product Designer', 'More ways to be heard.', 'An accessible communication tool inspired by my son’s wait for an AAC device, built to support expression and connection.', 'https://talkeez.org'],
 ['Sites & Wonders', 'WEB DEVELOPMENT', 'Full-Stack Developer', 'A thoughtful presence on the web.', 'Custom web solutions for events, ministries, and community organizations, shaped around the people they serve.']
];
const projectLogos = { DailyActivity: '/daily-activity-logo.png', 'Talkeez AAC': '/talkeez-logo.png', 'Sites & Wonders': '/sites-and-wonders-logo.png' };
function App(){return <>
<a className="skip-link" href="#main">Skip to content</a>
<header><a className="brand identity" href="#home" aria-label="Essential Networker, home"><img src="/enetworker-logo.svg" alt="EN — Essential Networker" /></a><nav aria-label="Main navigation"><a href="#story">My story</a><a href="#work">Selected work</a><a href="#resume">Experience</a><a href="#resources">Free resources</a></nav><a href="#contact">Let’s connect ↗</a></header>
<main id="main">
<section id="home" className="hero wrap"><div><p className="eyebrow">DEVELOPER. FOUNDER. FATHER.</p><h1>The architect<br/>of <em>understanding.</em></h1><p className="intro">I’m Josh—a dad and developer who knows how personal the right support can be. My son inspired me to build tools that help families communicate, share the little details, and feel more connected.</p><p className="muted">Building tools that help families, educators, and children with special needs thrive.</p><div className="actions"><a className="button" href="#work">Explore my work ↗</a><a href="#contact">Work with Joshua ↗</a></div><p className="location">BASED IN OWINGS MILLS, MARYLAND</p></div><figure><img className="portrait" src="/joshua-cassell-professional.png" alt="Joshua Cassell wearing glasses, a dark turtleneck, and a blazer"/><figcaption><span>Technology with purpose.</span><span>People at the center.</span></figcaption></figure></section>
<div className="ecosystem" aria-label="Projects and brands"><img className="ecosystem-identity" src="/enetworker-logo.svg" alt="EN — Essential Networker" />{projects.map(([name]) => <div className={`ecosystem-logo logo-${name === 'DailyActivity' ? 'daily' : name === 'Talkeez AAC' ? 'talkeez' : 'sites'}`} key={name}><img src={projectLogos[name]} alt={`${name} logo`} /></div>)}</div>
<section id="story" className="wrap section"><div className="section-heading"><p className="eyebrow">01 / THE STORY BEHIND THE WORK</p><span>A personal perspective</span></div><div className="columns"><div><h2>Good technology<br/>starts with<br/><em>showing up.</em></h2><blockquote>A former boss once told me that one of my greatest abilities was availability.<cite>A lesson that continues to shape my work.</cite></blockquote></div><article><p className="intro">The work I care about most starts close to home.</p><p>I was born in Brooklyn, New York, and raised on Long Island. My father, a businessman, showed me the importance of relationships. My mother, a teacher, taught me patience and the value of listening. Those lessons still shape how I show up—as a father, a developer, and someone who wants to be useful.</p><p>Later, a boss who taught me a great deal recognized availability as one of my strengths. That observation stayed with me. Being willing to listen, help, and follow through continues to shape how I work with people and approach the tools I build.</p><details><summary>Read the full story <span>+</span></summary><h3>From accounting to creating</h3><p>My early studies at Rutgers focused on accounting. I later turned toward software development and the Rutgers Coding Bootcamp, discovering a way to combine problem-solving with work that could make a practical difference.</p><h3>A personal reason to build</h3><p>When my youngest son was diagnosed with autism in 2020, my family began navigating new routines, services, and ways of communicating. Along the way, I noticed how much important information lived on paper, spread across the people supporting him.</p><p>My mother’s experience in special education helped me understand the demands on teachers and classroom staff. Families and educators needed ways to share observations and maintain continuity in everyday care.</p><h3>Tools inspired by everyday needs</h3><p>Talkeez AAC grew out of my son’s wait for a communication device. I wanted to create an accessible tool that could support expression while families explored the communication options available to them.</p><p>DailyActivity grew from a related need: bringing routines, behavior observations, learning progress, and communication moments together. Its purpose is to help the people around a child share a clearer picture of daily life, from the classroom to a weekend with grandparents.</p><h3>Faith, service, and availability</h3><p>My faith grounds my commitment to service. I want to build useful tools, stay open to what families and educators teach me, and show up for the work that matters. For me, the architecture of understanding begins there.</p></details></article></div></section>
<section id="work" className="section work"><div className="wrap"><p className="eyebrow">02 / SELECTED WORK</p><h2>Built with intention.<br/><em>Made for people.</em></h2><div className="project-grid">{projects.map(([name, category, role, tagline, description, url], i)=><article className="project" key={name}><div className="project-top"><p className="eyebrow">{category}</p><span>0{i+1}</span></div><div className={`project-logo logo-${name === 'DailyActivity' ? 'daily' : name === 'Talkeez AAC' ? 'talkeez' : 'sites'}`}><img src={projectLogos[name]} alt={`${name} logo`} loading="lazy" /></div><h3>{name}</h3><p><strong>{tagline}</strong></p><p className="muted">{description}</p><div className="project-bottom"><span>{role}</span>{url?<a href={url} target="_blank" rel="noreferrer">Explore {name} ↗</a>:<a href="#contact">Discuss this work ↗</a>}</div></article>)}</div></div></section>
<section id="resume" className="section wrap columns"><div><p className="eyebrow">03 / EXPERIENCE & EXPERTISE</p><h2>A developer’s mind.<br/><em>A founder’s perspective.</em></h2><p className="muted">Full-stack .NET developer, SaaS founder, and autism advocate. I connect software architecture with the practical needs of the people using it.</p><a className="button" href={CV} download="Joshua-Cassell-Resume.pdf">Download résumé ↓</a></div><div><h3>Tools & disciplines</h3><div className="skills">{['C# / .NET / .NET Core','Angular','Metadata engineering','SQL Server','PostgreSQL','Oracle','Azure DevOps CI/CD','Multi-tenant SaaS','Accessible technology'].map(s=><span key={s}>{s}</span>)}</div><details><summary>Background & education <span>+</span></summary><p>Founder — DailyActivity & Talkeez AAC<br/>Developer — Sites & Wonders<br/>Former Program Support — Philadelphia Youth Network</p><p>Rutgers Coding Bootcamp — Full-Stack Web Development<br/>Rutgers University — Early studies in Accounting</p></details></div></section>
<section id="resources" className="section resources"><div className="wrap columns"><div><p className="eyebrow">04 / SOMETHING USEFUL, FREELY SHARED</p><h2>A little more support<br/>for <em>everyday life.</em></h2><p>A printable autism family resource pack for organizing routines, sharing observations, and helping caregivers get to know your child.</p><a className="button light" href="/autism-resource-pack.html" download>Get the free resource pack ↓</a><a className="preview" href="/autism-resource-pack.html" target="_blank" rel="noreferrer">Preview & print ↗</a><small>Free HTML download · Print or save as PDF · No signup</small></div><div className="resource-list">{['Behavior & communication observation guide','Morning, evening & school-day routines','Printable communication cards','Babysitter & grandparent care sheets','Support-finding worksheet','Optional faith-friendly encouragement'].map((s,i)=><div key={s}><span>0{i+1}</span><p>{s}</p></div>)}</div></div></section>
<section id="contact" className="section wrap contact"><p className="eyebrow">LET’S BUILD SOMETHING THAT MATTERS</p><h2>Good things begin<br/>with a <em>conversation.</em></h2><p>Have a project in mind, a shared mission, or a question about my work? I’d love to connect.</p><div className="actions"><a className="button" href={linkedin} target="_blank" rel="noreferrer">Connect on LinkedIn ↗</a><a href="https://github.com/jcssll" target="_blank" rel="noreferrer">View GitHub ↗</a></div></section>
</main><footer className="wrap"><a className="brand identity footer-identity" href="#home"><img src="/enetworker-logo.svg" alt="Essential Networker" /></a><p>© {new Date().getFullYear()} ENetworker.org · Joshua F. Cassell</p><a href="#home">Back to top ↑</a></footer></>}
export default App;
