name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test --if-present

      - name: Build Project
        run: npm run build

      # Optional: Deploy step (Netlify, Vercel, Firebase, or SCP)
      # Example: Upload build to production server via SSH
      # - name: Deploy to Production
      #   run: echo "Deploying to production..."
